[package]
name = "tracers"
version = "0.1.0"
authors = ["Shane Sniff <slsniff@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indicatif = "0.15.0"
png = "0.16.8"
rand = "0.8.3"